### ISSUE TITLE
Posts and about do not seem to work

### ISSUE THREAD

**Issue by crro** [EmielH/tale-hugo#1]
Hi,

I just installed this and I seem to be having an issue displaying posts and the about page, do you have any ideas as to what might be happening? Even tho I have posts in my posts folder when i load the server nothing appears in the list. Similarly it does not seem to detect that I have an about page. Thanks for the help!

**Comment by EmielH** [comment]
Thanks for using Tale! Without having a look at the source code of your site, it's hard to say why it's not working. Is your site working correctly when using a different theme?

Another suggestion is to ask at the Hugo forums at https://discourse.gohugo.io - there are many knowledgable people there; that might get you an answer quicker as I am probably the only one checking the Tale repository.

**Comment by crro** [comment]
I actually figured it out! In your layout/index.html instead of having `"Type" "post"` -> `"Type" "posts"` it actually works. Thanks

**Comment by EmielH** [comment]
This is not a bug in the theme. You should actually rename the folder containing your posts to `content/post` instead of altering the theme. All themes work with a folder called `post` for posts. Take a look at the example Hugo site used for the [Hugo themes website](https://themes.gohugo.io) here: https://github.com/gohugoio/HugoBasicExample

**Comment by olizilla** [comment]
@EmielH I just hit this too. The confusion was caused by following the official quickstart guide which tells you to run 

```console
$ hugo new posts/my-first-post.md
```
https://gohugo.io/getting-started/quick-start/#step-4-add-some-content

Is the quickstart wrong? should it be `hugo new post/my-first-post.md` ?

**Comment by EmielH** [comment]
@olizilla Well spotted! It may be a bug in the theme after all. Apparently, the quickstart should be working correctly. See https://github.com/gohugoio/hugoDocs/issues/436

I will investigate! I don't think changing `post` to `posts` is the solution because that will break the theme on the theme site, so there is probably a different way to get the correct type name.

**Comment by crro** [comment]
Yes @olizilla, I later looked at the quickstart and that is why it was not working for me. Cool, thanks for investigating @EmielH

**Comment by EmielH** [comment]
@crro @olizilla Could you check if this now works correctly for you?

**Comment by lizhuohua** [comment]
@EmielH Hi, since you iterate all the pages, right now the about page will also be listed on the index page.

**Comment by EmielH** [comment]
Thanks for spotting this! I'm sure I tested it... I will look into this issue again!

**Comment by EmielH** [comment]
@lizhuohua I have a test site that has a few regular pages and the about page, and the about page does not show up in the posts lists. Be sure to put the about page in `content/about/_index.md` and the regular posts in `content/posts/` or `content/post/`. Can you let me know if this works for you?

**Comment by lizhuohua** [comment]
@EmielH Thanks a lot! It works. I put my about page in the wrong directory!
