### ISSUE TITLE
How to customize theme styles?

### ISSUE THREAD

**Issue by deniskyashif** [EmielH/tale-hugo#13]
I like this theme a lot, but would like to tweak it a little bit. Is there a way to add my own stylesheet in order to override some of the existing rules or add new ones?

**Comment by EmielH** [comment]
Thank you for your kind comment! At the moment, it's not possible to add your own stylesheet. I know several themes that offer configuration options to add additional stylesheets; I will look into this.

In the meantime, Hugo allows for overriding files from the theme. For example, to override `<yoursite>/themes/tale/assets/scss/tale/_base.scss`, create a file `<yoursite>/assets/scss/tale/_base.scss` and Hugo will use that file instead of the one provided by the theme. Make sure to copy the original styles over to your customized file and then alter them, as overriding is based on entire files only.

**Comment by deniskyashif** [comment]
Hey, thanks a for the reply! The way I did it was my css file in ```assets/```, overrode ```head.html``` with by copying the one from the theme to ```/layouts/partials``` and included my stylesheet there using ```<link rel="stylesheet" href="{{ "assets/my.css" | relURL }}">```.

**Comment by EmielH** [comment]
That's also a good option! :+1:

I'm going to leave this issue open as reminder to add support for custom stylesheets to the theme.

**Comment by EmielH** [comment]
For everyone following this issue: this feature has just been released in [version 1.1.0](https://github.com/EmielH/tale-hugo/releases/tag/v1.1.0) of the theme.
