### ISSUE TITLE
About page added to index

### ISSUE THREAD

**Issue by huyvohcmc** [EmielH/tale-hugo#18]
I created the about page by the command `hugo new about.md` but noticed that the post is added to the index of the blog while it shouldn't. What is the correct way to do it?

**Comment by EmielH** [comment]
The about page should reside in `content/about/_index.md`. This prevents it from showing up in the posts list.

**Comment by huyvohcmc** [comment]
@EmielH When I host Hugo site on Github static page, there is no about file created (I used `hugo` to build). Can you share with me the correct directory structure in this case?

Mine is:

```
content/
  about/
    _index.md
  posts/
    first-post.md
themes/
config.toml
```

**Comment by EmielH** [comment]
This directory structure looks fine to me. Unfortunately, I don't have any experience with Github Pages. I think you'll have better chances of getting a useful answer when you ask this question on the [Hugo Forums](https://discourse.gohugo.io). There are many knowledgeable people there, and some of them have probably used Github Pages as well.

**Comment by adampah** [comment]
I am still having the problem that the about page shows up on the index page as a blog post. Even when I try content/about/_index.md... does anyone know the solution? I tried reverting to a previous commit when this post was made and the problem is still there. It seems like all files in contents get displayed as blog posts. Does anyone know how to fix this?
