### ISSUE TITLE
Wrong behavior for links in summaries

### ISSUE THREAD

**Issue by efugier** [EmielH/tale-hugo#21]
## Links in summary do not work
```
---
...
summary: It's built [hugo](https://gohugo.io/), a very simple yet powerful static site generator framework and the [tale](https://themes.gohugo.io/tale/) theme.
---
```
=> 
![](https://i.imgur.com/y6Axetb.png)

-----

## Links insert something (linebreak ?) when using `<!--more-->`
```
---
...
---

It's built [hugo](https://gohugo.io/), a very simple yet powerful static site generator framework and the [tale](https://themes.gohugo.io/tale/) theme.

<!--more-->
```
=>
![](https://i.imgur.com/vmiNC9v.png)

**Comment by EmielH** [comment]
Thanks for bringing this to my attention. I will look into it!

**Comment by EmielH** [comment]
I made #23 to describe the issue that it's not possible to use Markdown in the summary variable in the page frontmatter. This is fixed.

As for using links in the summary, that's a different story. Since the entire summary is a link to the article, adding a link in the summary makes Hugo output invalid HTML that contains an `<a>` tag inside an `<a>`. This is not allowed.

The browser then "fixes" this invalid HTML by breaking up the different `<a>` tags so they're not nested anymore, which causes the weird layout.

I see a few options.

- Remove all links from summaries.
This makes it impossible to include a link in the summary, but also wouldn't break the HTML. I guess you actually _want_ to have a link in the summary, so this appears to not really be an option.
- Make only the title of the article clickable. 
The user cannot click on the summary anymore to read the article. This allows for links inside the summary. However, this makes the theme behave differently than the Jekyll theme I ported it from.
- Include a "Read more..." link.
This is something that also isn't in the original theme.

Maybe it's not such a big deal to have the theme behave differently than the original. I'm going to think about this a little. Feel free to share your ideas!

**Comment by efugier** [comment]
Thanks for investigating !

> Remove all links from summaries. [...] I guess you actually want to have a link in the summary [...]

> However, this makes the theme behave differently than the Jekyll theme I ported it from.

Yes, I'd want to have links in the summary but that's a personal need. Most users would probably rather keep the original behaviour because it's more functional and having links in the summary is very situational.

I think it's best to keep things the way they are !

**Comment by EmielH** [comment]
Fortunately, Hugo is very flexible. [The `<a>` tags for the post summaries are defined here](https://github.com/EmielH/tale-hugo/blob/7c1febd66ab49de2102ab02e258ca8752ed795f9/layouts/_default/summary.html#L1) -- feel free to create this file in your own project to override the theme's default summary. Put 
```
<a href="{{ .Permalink }}">...</a>
```
around the part that you want to link to the article. Maybe some additional styling is needed to preserve the look of the theme, since the  current`<a>` tag does have a class. Maybe changing that to a `<div>` is sufficient.

**Comment by efugier** [comment]
Thanks for the advices, I'll dig into it :)
