### ISSUE TITLE
A link on the summary mess up the styling in index page

### ISSUE THREAD

**Issue by Nimamoh** [EmielH/tale-hugo#37]
I have a lot of post with links at the beginning (e.g: on the summary)

It appears to mess up with the front page:

![image](https://user-images.githubusercontent.com/16213090/87476910-7bb97f80-c627-11ea-9dca-ffec3704608a.png)

**Comment by EmielH** [comment]
Hi @Nimamoh, this problem was reported before in #21. At the time I didn't really see a solution. The problem is that the entire summary links to the article. If you then use a link inside the summary, this creates nested `<a>` tags, which is not valid HTML.

Issue #21 contains some ideas how you can fix this for your own site. If you have any additional ideas on how I could fix that in the theme, feel free to let me know!

**Comment by Nimamoh** [comment]
Oh, sorry for the dupe. If I find something useful to share I'll do. Thank you.

**Comment by EmielH** [comment]
No worries! 👍
